### ISSUE TITLE
Conversion error with collections

### ISSUE THREAD

**Issue by MartinOpde** [OmarMuscatello/SimplePatch#7]
If I have a class like this : 

```c#
public class Sample
{
  public string Item1 {get;set;}
  public string item2 {get;set;}
  public ICollection<OtherObject> Item3 {get;set;}
}
```

I have this error : 
```
System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at SimplePatch.Delta`1.SetPropertiesValue(TEntity entity)
   at SimplePatch.Delta`1.Patch(TEntity entity)
```

Coming from this line I guess : https://github.com/OmarMuscatello/SimplePatch/blob/6711bba74aa131cf32bd17264d9b451012d9f4bf/src/SimplePatch/Delta.cs#L246

I think you should test if type is IEnumerable and then loop to update every properties.  Or do you have another solution?

**Comment by OmarMuscatello** [comment]
Hi @MartinOpde,
thank you for reporting this. Could you please provide the entire code?

**Comment by MartinOpde** [comment]
Unfortunately I cannot post publicly the entire code but it is nothing fancy.

```c#
public async Task<ActionResult<Sample>> Patch(string id, [FromBody] SimplePatch.Delta<Sample> patch)
        {
           var original = await LookupAsync(id);

            // Omitted code for brevity

            patch.Patch(original);

           return original;
        }
```

If i do this in startup.cs : 
```c#
DeltaConfig.Init(cfg => {
                cfg.AddEntity<Sample>().Property(x => x.Item3).AddMapping((propertyType, newValue) =>
                {
                    var res = new MapResult<ICollection<OtherObject>>();

                    var deserializedObject = Newtonsoft.Json.JsonConvert.DeserializeObject<ICollection<OtherObject>>(newValue.ToString());
                    res.Value = deserializedObject;

                    return res;
                });
            });
```
It does not throws exception but it override the old values with null or default;

**Comment by OmarMuscatello** [comment]
Thank you @MartinOpde.
SimplePatch doesn't support interaction with lists in general. However, I'm working on a fix to this.

**Comment by MartinOpde** [comment]
Ok thank you @OmarMuscatello.  When do your fix will be available you think?
Can you please keep me informed ?

**Comment by OmarMuscatello** [comment]
Hi @MartinOpde , sorry for delay response. I don't have an estimation for that. Of course, I will update you on news. Thank you for your patience.

**Comment by ChristopherLenz** [comment]
@OmarMuscatello and @MartinOpde 
Any solution for that problem? I implemented SimplePatch months ago (thanks for this great lib) and now I need also the support for lists

**Comment by agustin-giacchello** [comment]
@ChristopherLenz Hi, how did you make work the lists?

**Comment by ChristopherLenz** [comment]
> @ChristopherLenz Hi, how did you make work the lists?

You can have a look here: https://gist.github.com/ChristopherLenz/2226200307a1fdd10f0eb1ee35c3c5b0

**Comment by agustin-giacchello** [comment]
> > @ChristopherLenz Hi, how did you make work the lists?
> 
> You can have a look here: https://gist.github.com/ChristopherLenz/2226200307a1fdd10f0eb1ee35c3c5b0

Hi again, thank you for your sharing. I had implemented something similiar but the problem was that it overrides all the old values..

@OmarMuscatello do you have any advance regarding this issue?

**Comment by OvidiuACosma** [comment]
Omar,
I recently upgraded to NET Core 3.0.
Now, the Patch constantly fails with"Object must Implement IConvertible".
I've got your test project, upgraded to NETCore 3, and I get this:

{"Object must implement IConvertible."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147467262
    HelpLink: null
    InnerException: null
    Message: "Object must implement IConvertible."
    Source: "System.Private.CoreLib"
    StackTrace: "   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)\r\n   at SimplePatch.Delta`1.SetPropertiesValue(TEntity entity)\r\n   at SimplePatch.Delta`1.Patch(TEntity entity)\r\n   at SimplePatch.Examples.Core2.WebAPI.Controllers.PersonsController.<Patch>d__5.MoveNext() in C:\\Users\\ovidiucosma\\source\\repos\\SimplePatch\\examples\\SimplePatch.Examples.Core2.WebAPI\\SimplePatch.Examples.Core2.WebAPI\\Controllers\\PersonsController.cs:line 67"
    TargetSite: {System.Object ChangeType(System.Object, System.Type, System.IFormatProvider)}.

And seems it comes (as MartinOpde identified, too), from " propertyInfo.SetValue(entity, Convert.ChangeType(newPropertyValue, truePropertyType)); ".

Any news with this?

**Comment by OvidiuACosma** [comment]
:) and finally, it was all related to the new default Microsoft's System.Text.Json... which arrived to 'cannot convert from System.Text.Json.JsonElement to System.String'.
Came back to NewtonSoftJson and evrything's brilliant :)
Thanks.
